//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectU.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectU.Core.Resources.ModelValidation", typeof(ModelValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дедлайн має бути в майбутньому.
        /// </summary>
        internal static string FutureDate_AssignmentDeadline {
            get {
                return ResourceManager.GetString("FutureDate_AssignmentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка має бути від 0 до 100.
        /// </summary>
        internal static string Range_GradeValue {
            get {
                return ResourceManager.GetString("Range_GradeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дисципліну.
        /// </summary>
        internal static string Required_AssignmentCourse {
            get {
                return ResourceManager.GetString("Required_AssignmentCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дедлайн обов&apos;язковий.
        /// </summary>
        internal static string Required_AssignmentDeadline {
            get {
                return ResourceManager.GetString("Required_AssignmentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис завдання обов&apos;язковий.
        /// </summary>
        internal static string Required_AssignmentDescription {
            get {
                return ResourceManager.GetString("Required_AssignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва завдання обов&apos;язкова.
        /// </summary>
        internal static string Required_AssignmentTitle {
            get {
                return ResourceManager.GetString("Required_AssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть групу.
        /// </summary>
        internal static string Required_CourseGroup {
            get {
                return ResourceManager.GetString("Required_CourseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва дисципліни обов&apos;язкова.
        /// </summary>
        internal static string Required_CourseName {
            get {
                return ResourceManager.GetString("Required_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть викладача.
        /// </summary>
        internal static string Required_CourseTeacher {
            get {
                return ResourceManager.GetString("Required_CourseTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я обов&apos;язкове.
        /// </summary>
        internal static string Required_FirstName {
            get {
                return ResourceManager.GetString("Required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дисципліну.
        /// </summary>
        internal static string Required_GradeCourse {
            get {
                return ResourceManager.GetString("Required_GradeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть студента.
        /// </summary>
        internal static string Required_GradeStudent {
            get {
                return ResourceManager.GetString("Required_GradeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка обов&apos;язкова.
        /// </summary>
        internal static string Required_GradeValue {
            get {
                return ResourceManager.GetString("Required_GradeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва групи обов&apos;язкова.
        /// </summary>
        internal static string Required_GroupName {
            get {
                return ResourceManager.GetString("Required_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть завдання.
        /// </summary>
        internal static string Required_LabWorkAssignment {
            get {
                return ResourceManager.GetString("Required_LabWorkAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дисципліну.
        /// </summary>
        internal static string Required_LabWorkCourse {
            get {
                return ResourceManager.GetString("Required_LabWorkCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть студента.
        /// </summary>
        internal static string Required_LabWorkStudent {
            get {
                return ResourceManager.GetString("Required_LabWorkStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва роботи обов&apos;язкова.
        /// </summary>
        internal static string Required_LabWorkTitle {
            get {
                return ResourceManager.GetString("Required_LabWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище обов&apos;язкове.
        /// </summary>
        internal static string Required_LastName {
            get {
                return ResourceManager.GetString("Required_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дисципліну.
        /// </summary>
        internal static string Required_ScheduleCourse {
            get {
                return ResourceManager.GetString("Required_ScheduleCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час завершення обов&apos;язковий.
        /// </summary>
        internal static string Required_ScheduleEnd {
            get {
                return ResourceManager.GetString("Required_ScheduleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть групу.
        /// </summary>
        internal static string Required_ScheduleGroup {
            get {
                return ResourceManager.GetString("Required_ScheduleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час початку обов&apos;язковий.
        /// </summary>
        internal static string Required_ScheduleStart {
            get {
                return ResourceManager.GetString("Required_ScheduleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва має бути від 3 до 200 символів.
        /// </summary>
        internal static string StringLength_AssignmentTitle {
            get {
                return ResourceManager.GetString("StringLength_AssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва має бути від 3 до 200 символів.
        /// </summary>
        internal static string StringLength_CourseName {
            get {
                return ResourceManager.GetString("StringLength_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я від 2 до 50 символів.
        /// </summary>
        internal static string StringLength_FirstName {
            get {
                return ResourceManager.GetString("StringLength_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва має бути від 2 до 50 символів.
        /// </summary>
        internal static string StringLength_GroupName {
            get {
                return ResourceManager.GetString("StringLength_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва має бути від 3 до 200 символів.
        /// </summary>
        internal static string StringLength_LabWorkTitle {
            get {
                return ResourceManager.GetString("StringLength_LabWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище від 2 до 50 символів.
        /// </summary>
        internal static string StringLength_LastName {
            get {
                return ResourceManager.GetString("StringLength_LastName", resourceCulture);
            }
        }
    }
}
